package eo;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 28 23:59:02 AST 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PatientsImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PatientId,
        Name,
        Phone,
        Email,
        registrationStatus,
        Gender,
        Appointments;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PATIENTID = AttributesEnum.PatientId.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int PHONE = AttributesEnum.Phone.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int REGISTRATIONSTATUS = AttributesEnum.registrationStatus.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int APPOINTMENTS = AttributesEnum.Appointments.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PatientsImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("eo.Patients");
    }


    /**
     * Gets the attribute value for PatientId, using the alias name PatientId.
     * @return the value of PatientId
     */
    public String getPatientId() {
        return (String) getAttributeInternal(PATIENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PatientId.
     * @param value value to set the PatientId
     */
    public void setPatientId(String value) {
        setAttributeInternal(PATIENTID, value);
    }

    /**
     * Gets the attribute value for Name, using the alias name Name.
     * @return the value of Name
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Name.
     * @param value value to set the Name
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for Phone, using the alias name Phone.
     * @return the value of Phone
     */
    public String getPhone() {
        return (String) getAttributeInternal(PHONE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Phone.
     * @param value value to set the Phone
     */
    public void setPhone(String value) {
        setAttributeInternal(PHONE, value);
    }

    /**
     * Gets the attribute value for Email, using the alias name Email.
     * @return the value of Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Email.
     * @param value value to set the Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }


    /**
     * Gets the attribute value for registrationStatus, using the alias name registrationStatus.
     * @return the value of registrationStatus
     */
    public String getregistrationStatus() {
        if (getPhone () == null || getPhone().isEmpty())
             return "Incomplete Profile !!!";
        else
            return "Active Patient";
}

    /**
     * Sets <code>value</code> as the attribute value for registrationStatus.
     * @param value value to set the registrationStatus
     */
    public void setregistrationStatus(String value) {
        setAttributeInternal(REGISTRATIONSTATUS, value);
    }

    /**
     * Gets the attribute value for Gender, using the alias name Gender.
     * @return the value of Gender
     */
    public String getGender() {
        return (String) getAttributeInternal(GENDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gender.
     * @param value value to set the Gender
     */
    public void setGender(String value) {
        setAttributeInternal(GENDER, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getAppointments() {
        return (RowIterator) getAttributeInternal(APPOINTMENTS);
    }


    /**
     * @param patientId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String patientId) {
        return new Key(new Object[] { patientId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }
}

